CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuarios
    WHERE id = auth.uid()
      AND ativo = true
      AND role IN ('admin', 'instrutor', 'financeiro')
  );
$$;

REVOKE ALL ON FUNCTION public.is_staff() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated;

CREATE TABLE IF NOT EXISTS public.aulas_treinos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aula_id integer NOT NULL REFERENCES public.aulas(id) ON DELETE CASCADE,
  ficha_id integer NOT NULL REFERENCES public.fichas_treino(id) ON DELETE CASCADE,
  criado_em timestamp without time zone NOT NULL DEFAULT now(),
  atualizado_em timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT aulas_treinos_aula_unique UNIQUE (aula_id)
);
CREATE INDEX IF NOT EXISTS idx_aulas_treinos_ficha_id ON public.aulas_treinos(ficha_id);

ALTER TABLE public.aulas_treinos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "staff_all_aulas_treinos" ON public.aulas_treinos;
CREATE POLICY "staff_all_aulas_treinos" ON public.aulas_treinos
FOR ALL TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());

DO $$
DECLARE
  t text;
  tables_to_secure text[] := ARRAY[
    'alunos','aulas','avaliacoes','avaliacao_documentos','contas_pagar','categorias_contas',
    'categorias_receitas','config_estudio','config_juros','documentos','enderecos','eventos',
    'exercicios','ficha_exercicios','fichas_treino','formas_pagamento','lista_espera','mensalidades',
    'metas','outras_receitas','parcelas','planos','planos_alunos','planos_horarios','saude_alunos',
    'aulas_agendadas','capacidade_horario','controle_faltas','historico_renovacoes','matriculas',
    'aulas_treinos'
  ];
BEGIN
  FOREACH t IN ARRAY tables_to_secure LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
      EXECUTE format('DROP POLICY IF EXISTS "Acesso público para desenvolvimento" ON public.%I', t);
      EXECUTE format('DROP POLICY IF EXISTS "Enable read access for all users on %s" ON public.%I', t, t);
      EXECUTE format('DROP POLICY IF EXISTS "staff_all_%s" ON public.%I', t, t);
      EXECUTE format('CREATE POLICY "staff_all_%s" ON public.%I FOR ALL TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff())', t, t);
    END IF;
  END LOOP;
END $$;

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "usuarios_self_select" ON public.usuarios;
DROP POLICY IF EXISTS "usuarios_self_update" ON public.usuarios;
CREATE POLICY "usuarios_self_select" ON public.usuarios
FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "usuarios_self_update" ON public.usuarios
FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

ALTER TABLE public.sessoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "staff_all_sessoes" ON public.sessoes;
CREATE POLICY "staff_all_sessoes" ON public.sessoes
FOR ALL TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());

ALTER TABLE public.logs_auditoria ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "staff_all_logs_auditoria" ON public.logs_auditoria;
CREATE POLICY "staff_all_logs_auditoria" ON public.logs_auditoria
FOR ALL TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());

ALTER TABLE public.relatorios_gerados ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "staff_all_relatorios_gerados" ON public.relatorios_gerados;
CREATE POLICY "staff_all_relatorios_gerados" ON public.relatorios_gerados
FOR ALL TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());
